### ISSUE TITLE
Input for pysteps

### ISSUE THREAD

**Issue by winash12** [pySTEPS/pysteps#314] opened 2022-10-28 08:39 UTC
I have radar GIF files of reflectivity as shown here - From the mch example it appears pysteps can read GIF files and it is not necessary to have h5 files or netCDF files. Can it read a GIF file as shown below ? 
![caz_lkn](https://user-images.githubusercontent.com/9129700/198543756-e8dd8804-cad7-42f6-9f40-aa96fab00f80.gif)

**Comment by aperezhortal** [comment] 2022-10-28 11:18
Hello @winash12 , 

Pysteps can read raw MCH data stored as gif files. Note that this is not the same format as the image that you showed above.

I don't think is possible to read the file that you are showing since it contains text that is masking radar data. 
You mentioned in another issue that you have netCDF and HDF5 files. I suggest you use those formats. 
However, you may need to create your own importer (see https://pysteps.readthedocs.io/en/stable/developer_guide/importer_plugins.html ).

**Comment by dnerini** [comment] 2022-10-28 11:31
Duplicate of #20?

**Comment by winash12** [comment] 2022-10-29 11:31
So reopening for a short while. There is some hope that scikit image could convert my image into a GIF without the background and keeping the reflectivity alone. We will see if that works or not. The geo encoding could be saved as well with scikit image. We will see no promises or guarantees. Just looking at a POC.

**Closed as completed** 2022-11-26 02:38 UTC
