### ISSUE TITLE
Unable to import data

### ISSUE THREAD

**Issue by wxguy** [pySTEPS/pysteps#426] opened 2024-08-20 19:01 UTC
This is in continuation of the issue I have reported earlier in https://github.com/pySTEPS/pysteps/issues/420. I understood from a lot of reading that I have to create a plugin for dealing with my data set. I have already created the required plugin and tested with static input file for loading data and returning the values as per mandated importer standards of PySTEPS. Now, I am stuck at loading all my datasets. 

Here is the list of files I am trying to import:-

```
$ ls                                                                                         

3DIMG_18062024_0000_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0200_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0400_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0700_L1C_ASIA_MER_V01R00.h5  
3DIMG_18062024_0030_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0230_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0530_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0730_L1C_ASIA_MER_V01R00.h5
3DIMG_18062024_0100_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0300_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0600_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0800_L1C_ASIA_MER_V01R00.h5
3DIMG_18062024_0130_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0330_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0630_L1C_ASIA_MER_V01R00.h5  3DIMG_18062024_0830_L1C_ASIA_MER_V01R00.h5
```

Here is my `pystepsrc.json` file content with respect to loading of above data:-

```
"insat_imager": {
      "root_path": "/mnt/Data/myprojects/nowcast/data", 
      "path_fmt": "/",
      "fn_pattern": "3DIMG_%d%m%Y_%H%M_L1C_ASIA_MER_V01R00",
      "fn_ext": "h5",
      "importer": "insat_imager",
      "timestep": 30,
      "importer_kwargs": {}
    }
```

Here is portion of script I am trying to load (referred from https://pysteps.readthedocs.io/en/stable/auto_examples/plot_steps_nowcast.html#sphx-glr-auto-examples-plot-steps-nowcast-py) example:-

```
from datetime import datetime
import pysteps
from pysteps import io, nowcasts, rcparams
import time

config_file_path = pysteps.load_config_file("pystepsrc.json", verbose=True)
date = datetime.strptime("18062024", "%d%m%Y")

# print(datetime.strptime('20240618', '%Y%m%d'))

data_source = config_file_path.data_sources["insat_imager"]
root_path = data_source["root_path"]
path_fmt = data_source["path_fmt"]
fn_pattern = data_source["fn_pattern"]
fn_ext = data_source["fn_ext"]
importer_name = data_source["importer"]
importer_kwargs = data_source["importer_kwargs"]

# Unable to load files
fns = io.archive.find_by_date(date, root_path, path_fmt, fn_pattern, fn_ext, timestep=5, num_prev_files=0)
```

When I execute the above code, I get the following error:-

```
file not found: None
Traceback (most recent call last):
  File "/mnt/Data/myprojects/nowcast/nowcast_test.py", line 43, in <module>
    fns = io.archive.find_by_date(date, root_path, path_fmt, fn_pattern, fn_ext, timestep=5, num_prev_files=0)
  File "/home/sundar/miniconda3/envs/pysteps/lib/python3.10/site-packages/pysteps/io/archive.py", line 85, in find_by_date
    raise IOError("no input data found in %s" % root_path)
OSError: no input data found in /mnt/Data/myprojects/nowcast/data

```

Can someone guide me in right direction to solve the issue.

**Comment by dnerini** [comment] 2024-08-21 21:26
hi @wxguy, it looks like there is something wrong in the parameters you're passing to the `find_by_date` function, which is then building the wrong path to your data. I suspect the problem is caused by `"path_fmt": "/"`, can you try changing it to `"path_fmt": ""` and report back what you get?

also, why `timestep=5`? shouldn't be `timestep=30` instead?

**Comment by dnerini** [comment] 2024-08-26 19:27
Closing this for now @wxguy, feel free to reopen in case you need more help!

**Closed as completed by dnerini** 2024-08-26 19:27 UTC
