### ISSUE TITLE
How to use pysteps with real case

### ISSUE THREAD

**Issue by phong9134** [pySTEPS/pysteps#100] opened 2019-07-24 04:42 UTC
Hi everyone,

I'm really fresh of this field, so I implemented pysteps with my data, but it is not like expecting result. I have some question about that
Hope you can consider it and give me some advice ( or some tutorials)

**Comment by dnerini** [comment] 2019-07-24 05:51
Hi @phong9134 and welcome to pysteps!

> I implemented pysteps with my data, but it is not like expecting result.

What kind of unexpected results are you obtaining? It would help if you could provide more detail, including the code and data that you are using in order to be able to recreate the issue that you are having.

> My data from 2 previous images which are arrays in 30 minutes( each 15 minutes, we have 1 image). Then I calculate motion field with VET, after that I apply it to forecast next 1 hour ( leadtimes=4 ).

From what I understand, you are doing all right: once you have imported your sequence of images, the correct workflow is to compute the motion field and then extrapolate the last image to produce the nowcast. You can find a simple example in the [pysteps gallery](https://pysteps.readthedocs.io/en/latest/auto_examples/plot_extrapolation_nowcast.html#sphx-glr-auto-examples-plot-extrapolation-nowcast-py) (that you probably already know), which in your case would give something like this:

```
from pysteps import motion, nowcasts, utils

# Estimate the motion field with VET
oflow_method = motion.get_method("VET")
V = oflow_method(R[-2:, :, :])

# Extrapolate the last radar observation
extrapolate = nowcasts.get_method("extrapolation")
R_f = extrapolate(R[-1, :, :], V, 4)

# Back-transform to rain rate
transform = utils.get_method("dB")
R_f, __ = transform(R_f, metadata, inverse=True)
```
I assumed that you had previously imported your data array R (with metadata) and transformed it into dB units (but you can use other data transformations methods, too, see [here](https://pysteps.readthedocs.io/en/latest/auto_examples/data_transformations.html#sphx-glr-auto-examples-data-transformations-py).

> Always use 2 previous images to calculate motion field?

It depends on the optical flow method: VET and Proesmans both require two images, by default DARTS requires at least 5 images, while Lucas-Kanade requires at least 2 images.

> And what are main point we need focus ( to change parameter )from code of pysteps gallery

First I would try to get the code working with your data and the default parameters. After this, in [VET](https://pysteps.readthedocs.io/en/latest/generated/pysteps.motion.vet.vet.html#pysteps.motion.vet.vet) you can start playing with the smooth_gain and sectors parameters, for example. If you are going to try ensemble nowcasting with STEPS (as in [here](https://pysteps.readthedocs.io/en/latest/auto_examples/plot_steps_nowcast.html#sphx-glr-auto-examples-plot-steps-nowcast-py)), there are many important parameters to adjust. You can find some good examples in the series of experiments that we have included in the [pysteps publication](https://www.geosci-model-dev-discuss.net/gmd-2019-94/).

Hope this helps!

**Comment by phong9134** [comment] 2019-07-24 10:00
Thank you so much @dnerini , 
About our result not good because it hasn't same any shape of our observation precipitation images. I really interest with this approach, maybe I think my implement not good, but I can't find any problem about code right now( I try to understand about this approach to improve). I can't share the code so sorry about that.

I have another question, hope you consider: I see on example gallery, it uses metadata, but in my data just have R array, do you think it has affect with my results?

I will try other transform ways as you mention. 

Again, thanks so much

**Comment by phong9134** [comment] 2019-07-25 03:36
This is my result, 2 first pictures in 30 minutes( each 15 minutes, I have 1 image. So with leadtimes = 4 to I predict next one hour. The final image has not good shape or motion I think
_
![Screenshot_1](https://user-images.githubusercontent.com/53001141/61843453-dbbe8f80-aec5-11e9-9b4d-fcb34c41f968.png)
_

**Comment by aperezhortal** [comment] 2019-07-25 11:54
Hi @phong9134, are you using MaskedArrays as input data? The forecast seems masked almost everywhere in the domain. 

In addition, the two input fields that you are using seems quite decorrelated to each other. Visually, it is difficult to see a motion pattern.  That is probably caused by the time difference between the precipitation fields used in VET.  

VET is a variational method that minimizes a cost function to find the motion vectors. If the input fields are highly decorrelated, VET will struggle to find a solution and it may converge to a secondary minimum, i.e., it will not converge to the optimal solution. 

Give a try LK method to see if it gives better results. 

Hope this help.

**Comment by phong9134** [comment] 2019-07-26 04:38
> Hi everyone,
> 
> I'm really fresh of this field, so I implemented pysteps with my data, but it is not like expecting result. I have some question about that.
> 
> My data from 2 previous images which are arrays in 30 minutes( each 15 minutes, we have 1 image). Then I calculate motion field with VET, after that I apply it to forecast next 1 hour ( leadtimes=4 ). So I have confuse about my way: **Always use 2 previous images to calculate motion field?**. And what are main point we need focus ( to change parameter )from code of pysteps gallery
> 
> Hope you can consider it and give me some advice ( or some tutorials)

**Comment by dnerini** [comment] 2019-07-28 08:31
> Give a try LK method to see if it gives better results.

I also advise trying different optical flow methods and see if one produces significantly better results. After all, this is precisely the advantage of using pysteps!

Also, try to pass the input fields using MaskedArrays with the LK method, too, and add a buffer to the mask to improve the retrieval of motion vectors nearby the limits of the radar mask. More info and example [here](https://pysteps.readthedocs.io/en/latest/auto_examples/LK_buffer_mask.html#sphx-glr-auto-examples-lk-buffer-mask-py).

**Comment by dnerini** [comment] 2019-08-07 07:46
I suggest to close the issue for now.

**Closed as completed by dnerini** 2019-08-07 07:46 UTC
Labels: support

**Comment by muheyyds** [comment] 2024-11-23 07:53
My data is dbz, how to convert it to fit the input
