### ISSUE TITLE
ModuleNotFoundError: No module named 'pysteps.motion._vet'

### ISSUE THREAD

**Issue by wcwoo** [pySTEPS/pysteps#40] opened 2019-02-15 13:25 UTC
Hi! Many thanks for making STEPS available.

I've successfully created Conda environment and completed `python setup.py install`. But when I tried to import pySTEPS, I encountered the following problem:

    (pysteps) wcwoo@wcwoo-VirtualBox:~/pysteps$ python
    Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 03:09:43) 
    [GCC 7.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pysteps
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "/home/wcwoo/pysteps/pysteps/__init__.py", line 15, in <module>
        from . import motion
      File "/home/wcwoo/pysteps/pysteps/motion/__init__.py", line 3, in <module>
        from .interface import get_method
      File "/home/wcwoo/pysteps/pysteps/motion/interface.py", line 5, in <module>
        from pysteps.motion.vet import vet
      File "/home/wcwoo/pysteps/pysteps/motion/vet.py", line 30, in <module>
        from pysteps.motion._vet import _warp, _cost_function
    ModuleNotFoundError: No module named 'pysteps.motion._vet'
    >>> 

I'm using Ubuntu LTS 18.04. Anything I've missed?

**Comment by dnerini** [comment] 2019-02-15 13:46
Hi @wcwoo!
What is your working directory?
I was able to reproduce your error when launching python from within the pysteps folder with the source code:
```
(pysteps) -bash-4.2$ pwd
/home/ned/pysteps
(pysteps) -bash-4.2$ python
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysteps
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/ned/pysteps/pysteps/__init__.py", line 15, in <module>
    from . import motion
  File "/home/ned/pysteps/pysteps/motion/__init__.py", line 3, in <module>
    from .interface import get_method
  File "/home/ned/pysteps/pysteps/motion/interface.py", line 5, in <module>
    from pysteps.motion.vet import vet
  File "/home/ned/pysteps/pysteps/motion/vet.py", line 30, in <module>
    from pysteps.motion._vet import _warp, _cost_function
ModuleNotFoundError: No module named 'pysteps.motion._vet'
>>>
```
Moving to any other folder avoids the error:

```
(pysteps) -bash-4.2$ cd examples/
(pysteps) -bash-4.2$ pwd
/home/ned/pysteps/examples
(pysteps) -bash-4.2$ python
Python 3.6.6 |Anaconda, Inc.| (default, Oct  9 2018, 12:34:16)
[GCC 7.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import pysteps
Pysteps configuration file found at: /home/ned/.pysteps/pystepsrc
>>>
```
I'm not sure what it's causing the problem, my guess is that there is some sort of path conflict when pysteps is imported from within its main directory. Do you have a better idea @aperezhortal? Is there an easy fix we can implement?

**Comment by wcwoo** [comment] 2019-02-15 13:58
My working directory was just `/home/wcwoo/pysteps`.  I confirm that invoking `python` from another directory avoids the problem. Thanks!

    (pysteps) wcwoo@wcwoo-VirtualBox:~/pysteps$ cd examples
    (pysteps) wcwoo@wcwoo-VirtualBox:~/pysteps/examples$ python
    Python 3.6.7 | packaged by conda-forge | (default, Nov 21 2018, 03:09:43) 
    [GCC 7.3.0] on linux
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pysteps
    Pysteps configuration file found at: /home/wcwoo/.local/lib/python3.6/site-packages/pysteps-0.2-py3.6-linux-x86_64.egg/pysteps/pystepsrc

**Comment by aperezhortal** [comment] 2019-02-15 14:30
Hi @wcwoo, this error is  caused by the root **pysteps** repository folder being recognized as the **pysteps package**.  Any directory on sys.path with a name that matches the package name (pysteps in this case) that is being looked for, will be recognized as contributing modules and sub-packages to that package. The error is happening because the the first directory in sys.path is the current working directory.

[More information about this here.](http://python-notes.curiousefficiency.org/en/latest/python_concepts/import_traps.html#the-missing-init-py-trap)

**Comment by dnerini** [comment] 2019-02-15 14:55
OK, so this is actually normal behavior rather than a bug. Thanks @aperezhortal for the explanation!

**Comment by wcwoo** [comment] 2019-02-15 14:57
I see. Thanks for your explanations.

**Closed as completed** 2019-02-15 14:57 UTC
Labels: support
